# Generated by Django 3.1.6 on 2021-02-15 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_guests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guests',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='guests',
            old_name='last_name',
            new_name='lastName',
        ),
    ]
