# Generated by Django 3.1.6 on 2021-02-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_auto_20210215_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guests',
            name='attending',
            field=models.BooleanField(),
        ),
    ]
